services:
  - type: web
    name: garys-website
    runtime: node
    plan: free
    buildCommand: npm install && npm run render-build
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_VERSION
        value: 20
